apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentkitproject-site.fullname" . }}
  labels:
    {{- include "agentkitproject-site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agentkitproject-site.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
